# Generated by Django 2.2.12 on 2020-06-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metarecord', '0045_populate_persistent_user_name_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classification',
            options={'permissions': (('can_edit_classification', 'Can edit classification'), ('can_review_classification', 'Can review classification'), ('can_approve_classification', 'Can approve classification'), ('can_view_classification_modified_by', 'Can view classification modified by')), 'verbose_name': 'classification', 'verbose_name_plural': 'classifications'},
        ),
    ]
